# h2 ??
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# DataSource ??
spring.datasource.url=jdbc:h2:mem:database
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
# clock ??
spring.clock.zone=Asia/Seoul
# jwt ??
jwt.secret=8mV9rQ2xKp7Ld4NzTt1YwE6uJc3Hs5BxQf0Ra8DnUv4
jwt.expiration-seconds=3600

